[package]
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
description = "An implementation of the lua bindings hash from Smash Ultimate"
edition = "2018"
license = "MIT"
name = "lua_bind_hash"
version = "1.0.1"

[dependencies]
